import random

chance = ['GO TO THE END', 'GO TO THE END', 'FREE FROM THE END', 'FREE FROM THE END', 'PAY 4 INGOTS', 'COLLECT 1 INGOT 5 NUGGETS PER COLOUR SET YOU OWN', 'PAY 5 NUGGETS PER SETTLEMENT AND 1 INGOT 5 NUGGETS PER CITY YOU OWN', 'TAKE A RIDE TO CASTLE VIEW', 'TAKE A RIDE TO MOTOR DRIVE', 'ADVANCE TO GO', 'PAY 4 INGOTS 5 NUGGETS', 'PAY 8 NUGGETS TO EACH PLAYER', 'PAY 1 INGOT PER PROPERTY YOU OWN', 'COLLECT 1 INGOT FROM EACH PLAYER', 'COLLECT 5 INGOTS', 'COLLECT 3 INGOTS 5 NUGETS', 'ADVANCE TO THE NEAREST UTILITY. IF OWNED, PAY OWNER 2 INGOTS. IF UNOWNED, YOU MAY BUY IT.', 'ADVANCE TO GO', 'TAKE A RIDE TO FORTUNE VALLEY', 'GOT TO THE ENDER PEARL. YOU MAY PAY 3 INGOTS TO USE IT', 'CHOSE A PLAYER AND PUT HIM ON YOUR PROPERTY FOR 1/2 THE RENT', 'PAY 2 INGOTS PER COLOUR SET YOU OWN', 'TAKE A RIDE TO BLING BEACH']
community = ['GO TO THE END', 'GO TO THE END', 'FREE FROM THE END', 'FREE FROM THE END', 'GO TO THE ENDER PEARL. YOU MAY PAY 3 INGOTS TO USE IT', 'CHOSE A PLAYER AND PUT HIM ON YOUR PROPERTY FOR 1/2 THE RENT', 'ADVANCE TO THE NEAREST UTILITY. IF OWNED, PAY OWNER 2 INGOTS. IF UNOWNED, YOU MAY BUY IT.', 'TAKE A RIDE TO SKI MOUNTAIN', 'COLLECT 5 INGOTS', 'PAY 1 INGOT PER PROPERTY YOU OWN', 'TAKE A RIDE TO ADVENTURE PARK', 'TAKE A RIDE TO PARTY PLAZA', 'COLLECT 3 INGOTS 5 NUGGETS', 'PAY 4 INGOTS', 'ADVANCE TO GO', 'PAY 5 NUGGETS PER SETTLEMENT AND 1 INGOT 5 NUGGETS PER CITY YOU OWN', 'PAY 2 INGOTS PER COLOUR SET YOU OWN', 'ADVANCE TO GO', 'COLLECT 1 INGOT 5 NUGGETS PER COLOUR SET YOU OWN', 'PAY 4 INGOTS 5 NUGGETS', 'COLLECT 1 INGOT FROM EACH PLAYER', "TAKE A RIDE TO SURFER'S COVE"]

def Chance():
    Chance_Len = len(chance)
    Ch = random.randint(0, Chance_Len - 1)
    return chance[Ch]

def Community_Chest():
    Community_Len = len(community)
    Co = random.randint(0, Community_Len - 1)
    return community[Co]

print(f'CHANCE: {Chance()}')
print(f'COMMUNITY CHEST: {Community_Chest()}')